[server]
65.0.92.150 ansible_user=ubuntu ansible_ssh_private_key_file=/mnt/d/DevOps/Practice/end-to-end-3tier-ecommerce-devops/terraform/batbazar-key.pem


; admin_url = "http://admin.ffindiano1.xyz"
; api_url = "http://api.ffindiano1.xyz"
; frontend_url = "http://ffindiano1.xyz"
; hosted_zone_id = "Z02043091WWB8VC0MT45J"
; instance_public_dns = "ec2-13.201.20.57.ap-south-1.compute.amazonaws.com"
; instance_public_ip = "65.0.92.150"
; name_servers = tolist([
;   "ns-1431.awsdns-50.org",
;   "ns-1875.awsdns-42.co.uk",
;   "ns-331.awsdns-41.com",
;   "ns-666.awsdns-19.net",
; ])


